// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"video_clip/cmd/comment/rpc/comment"
	"video_clip/cmd/comment/rpc/internal/logic"
	"video_clip/cmd/comment/rpc/internal/svc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) Comment(ctx context.Context, in *comment.CommentReq) (*comment.CommentRes, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}

func (s *CommentServer) DelComment(ctx context.Context, in *comment.DelCommentReq) (*comment.DelCommentRes, error) {
	l := logic.NewDelCommentLogic(ctx, s.svcCtx)
	return l.DelComment(in)
}

func (s *CommentServer) CommentList(ctx context.Context, in *comment.CommentListReq) (*comment.CommentListRes, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
