// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"
	comment2 "video_clip/cmd/comment/rpc/comment"
	"video_clip/cmd/comment/rpc/internal/logic"
	"video_clip/cmd/comment/rpc/internal/svc"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	comment2.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) Ping(ctx context.Context, in *comment2.Request) (*comment2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
