// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectCountFieldNames          = builder.RawFieldNames(&CollectCount{})
	collectCountRows                = strings.Join(collectCountFieldNames, ",")
	collectCountRowsExpectAutoSet   = strings.Join(stringx.Remove(collectCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectCountRowsWithPlaceHolder = strings.Join(stringx.Remove(collectCountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	collectCountModel interface {
		Insert(ctx context.Context, data *CollectCount) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CollectCount, error)
		FindOneByBizIdObjId(ctx context.Context, bizId string, objId int64) (*CollectCount, error)
		Update(ctx context.Context, data *CollectCount) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCollectCountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CollectCount struct {
		Id         int64     `db:"id"`          // 主键ID
		BizId      string    `db:"biz_id"`      // 业务ID
		ObjId      int64     `db:"obj_id"`      // 点赞对象id
		CollectNum int64     `db:"collect_num"` // 收藏数
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 最后修改时间
	}
)

func newCollectCountModel(conn sqlx.SqlConn) *defaultCollectCountModel {
	return &defaultCollectCountModel{
		conn:  conn,
		table: "`collect_count`",
	}
}

func (m *defaultCollectCountModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCollectCountModel) FindOne(ctx context.Context, id int64) (*CollectCount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectCountRows, m.table)
	var resp CollectCount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectCountModel) FindOneByBizIdObjId(ctx context.Context, bizId string, objId int64) (*CollectCount, error) {
	var resp CollectCount
	query := fmt.Sprintf("select %s from %s where `biz_id` = ? and `obj_id` = ? limit 1", collectCountRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, bizId, objId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectCountModel) Insert(ctx context.Context, data *CollectCount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, collectCountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BizId, data.ObjId, data.CollectNum)
	return ret, err
}

func (m *defaultCollectCountModel) Update(ctx context.Context, newData *CollectCount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectCountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.BizId, newData.ObjId, newData.CollectNum, newData.Id)
	return err
}

func (m *defaultCollectCountModel) tableName() string {
	return m.table
}
