// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vcVideoCollectFieldNames          = builder.RawFieldNames(&VcVideoCollect{})
	vcVideoCollectRows                = strings.Join(vcVideoCollectFieldNames, ",")
	vcVideoCollectRowsExpectAutoSet   = strings.Join(stringx.Remove(vcVideoCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vcVideoCollectRowsWithPlaceHolder = strings.Join(stringx.Remove(vcVideoCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheVcVideoCollectIdPrefix = "cache:vcVideoCollect:id:"
)

type (
	vcVideoCollectModel interface {
		Insert(ctx context.Context, data *VcVideoCollect) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VcVideoCollect, error)
		Update(ctx context.Context, data *VcVideoCollect) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVcVideoCollectModel struct {
		sqlc.CachedConn
		table string
	}

	VcVideoCollect struct {
		Id     int64 `db:"id"`      // id
		Uid    int64 `db:"uid"`     // 用户id
		PostId int64 `db:"post_id"` // 视频id
	}
)

func newVcVideoCollectModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVcVideoCollectModel {
	return &defaultVcVideoCollectModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`vc_video_collect`",
	}
}

func (m *defaultVcVideoCollectModel) Delete(ctx context.Context, id int64) error {
	vcVideoCollectIdKey := fmt.Sprintf("%s%v", cacheVcVideoCollectIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, vcVideoCollectIdKey)
	return err
}

func (m *defaultVcVideoCollectModel) FindOne(ctx context.Context, id int64) (*VcVideoCollect, error) {
	vcVideoCollectIdKey := fmt.Sprintf("%s%v", cacheVcVideoCollectIdPrefix, id)
	var resp VcVideoCollect
	err := m.QueryRowCtx(ctx, &resp, vcVideoCollectIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vcVideoCollectRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVcVideoCollectModel) Insert(ctx context.Context, data *VcVideoCollect) (sql.Result, error) {
	vcVideoCollectIdKey := fmt.Sprintf("%s%v", cacheVcVideoCollectIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, vcVideoCollectRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.PostId)
	}, vcVideoCollectIdKey)
	return ret, err
}

func (m *defaultVcVideoCollectModel) Update(ctx context.Context, data *VcVideoCollect) error {
	vcVideoCollectIdKey := fmt.Sprintf("%s%v", cacheVcVideoCollectIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vcVideoCollectRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.PostId, data.Id)
	}, vcVideoCollectIdKey)
	return err
}

func (m *defaultVcVideoCollectModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheVcVideoCollectIdPrefix, primary)
}

func (m *defaultVcVideoCollectModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vcVideoCollectRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVcVideoCollectModel) tableName() string {
	return m.table
}
