// Code generated by goctl. DO NOT EDIT.
// Source: post.proto

package postclient

import (
	"context"

	"video_clip/cmd/post/rpc/post"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Author                = post.Author
	CollectNumRequest     = post.CollectNumRequest
	CollectNumResponse    = post.CollectNumResponse
	CommentNumRequest     = post.CommentNumRequest
	CommentNumResponse    = post.CommentNumResponse
	GetHotVideoRequest    = post.GetHotVideoRequest
	GetHotVideoResponse   = post.GetHotVideoResponse
	GetTagListRequest     = post.GetTagListRequest
	GetTagListResponse    = post.GetTagListResponse
	GetVideoByUidRequest  = post.GetVideoByUidRequest
	GetVideoByUidResponse = post.GetVideoByUidResponse
	GetVideoListRequest   = post.GetVideoListRequest
	GetVideoListResponse  = post.GetVideoListResponse
	LikeNumRequest        = post.LikeNumRequest
	LikeNumResponse       = post.LikeNumResponse
	SearchVideoRequest    = post.SearchVideoRequest
	SearchVideoResponse   = post.SearchVideoResponse
	Tag                   = post.Tag
	UploadVideoRequest    = post.UploadVideoRequest
	UploadVideoResponse   = post.UploadVideoResponse
	VideoModel            = post.VideoModel

	Post interface {
		// 上传视频
		UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*UploadVideoResponse, error)
		// 获得视频 - 默认/分类
		GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
		// 获得热门视频
		GetHotVideoList(ctx context.Context, in *GetHotVideoRequest, opts ...grpc.CallOption) (*GetHotVideoResponse, error)
		// 根据用户id查找视频
		GetVideoByUid(ctx context.Context, in *GetVideoByUidRequest, opts ...grpc.CallOption) (*GetVideoByUidResponse, error)
		// 根据搜索查询视频
		SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error)
		// 获得类别
		GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error)
		// 评论数操作
		SetCommentNum(ctx context.Context, in *CommentNumRequest, opts ...grpc.CallOption) (*CommentNumResponse, error)
		// 点赞数操作
		SetLikeNum(ctx context.Context, in *LikeNumRequest, opts ...grpc.CallOption) (*LikeNumResponse, error)
		// 收藏数操作
		CollectNum(ctx context.Context, in *CollectNumRequest, opts ...grpc.CallOption) (*CollectNumResponse, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

// 上传视频
func (m *defaultPost) UploadVideo(ctx context.Context, in *UploadVideoRequest, opts ...grpc.CallOption) (*UploadVideoResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.UploadVideo(ctx, in, opts...)
}

// 获得视频 - 默认/分类
func (m *defaultPost) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.GetVideoList(ctx, in, opts...)
}

// 获得热门视频
func (m *defaultPost) GetHotVideoList(ctx context.Context, in *GetHotVideoRequest, opts ...grpc.CallOption) (*GetHotVideoResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.GetHotVideoList(ctx, in, opts...)
}

// 根据用户id查找视频
func (m *defaultPost) GetVideoByUid(ctx context.Context, in *GetVideoByUidRequest, opts ...grpc.CallOption) (*GetVideoByUidResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.GetVideoByUid(ctx, in, opts...)
}

// 根据搜索查询视频
func (m *defaultPost) SearchVideo(ctx context.Context, in *SearchVideoRequest, opts ...grpc.CallOption) (*SearchVideoResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.SearchVideo(ctx, in, opts...)
}

// 获得类别
func (m *defaultPost) GetTagList(ctx context.Context, in *GetTagListRequest, opts ...grpc.CallOption) (*GetTagListResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.GetTagList(ctx, in, opts...)
}

// 评论数操作
func (m *defaultPost) SetCommentNum(ctx context.Context, in *CommentNumRequest, opts ...grpc.CallOption) (*CommentNumResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.SetCommentNum(ctx, in, opts...)
}

// 点赞数操作
func (m *defaultPost) SetLikeNum(ctx context.Context, in *LikeNumRequest, opts ...grpc.CallOption) (*LikeNumResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.SetLikeNum(ctx, in, opts...)
}

// 收藏数操作
func (m *defaultPost) CollectNum(ctx context.Context, in *CollectNumRequest, opts ...grpc.CallOption) (*CollectNumResponse, error) {
	client := post.NewPostClient(m.cli.Conn())
	return client.CollectNum(ctx, in, opts...)
}
