// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"
	"video_clip/cmd/like/rpc/internal/logic"
	"video_clip/cmd/like/rpc/internal/svc"
	like2 "video_clip/cmd/like/rpc/like"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	like2.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Ping(ctx context.Context, in *like2.Request) (*like2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
