// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Mobile   string `json:"mobile"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token Token `json:"token"`
}

type GenerateTokenReq struct {
	UserId int64 `json:"userId,string"`
}

type GenerateTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Avatar        string `json:"avatar"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
	WorkCount     int64  `json:"work_count"`
}

type GetUserInfoReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserInfoRes struct {
	UserInfo User `json:"user_info"`
}

type UpdateUserInfoReq struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UpdateUserInfoRes struct {
}

type UploadVideoReq struct {
}

type UploadVideoRes struct {
	Avatar string `json:"avatar"`
}

type GetHotVideoListReq struct {
}

type GetHotVideoListRes struct {
}

type GetVideoListByCatagoryReq struct {
}

type GetVideoListByCatagoryRes struct {
}

type GetVideoListByTagReq struct {
}

type GetVideoListByTagRes struct {
}

type DownloadVideoReq struct {
}

type DownloadVideoRes struct {
}

type SendMsgReq struct {
}

type SendMsgRes struct {
}

type LikeReq struct {
	BizId    string `json:"bizId"`    // 业务id
	TargetId int64  `json:"targetId"` // 点赞对象id
	UserId   int64  `json:"userId"`   // 用户id
	LikeType int32  `json:"likeType"` // 点赞类型  0:点赞 1:点踩
}

type LikeRes struct {
}

type IsLikeReq struct {
	BizId    string `json:"bizId"`
	TargetId int64  `json:"targetId"`
	UserId   int64  `json:"userId"`
}

type IsLikeRes struct {
	UserLikes map[int64]string `json:"userLikes"`
}

type CancelLikeReq struct {
}

type CancelLikeRes struct {
}

type FollowReq struct {
	UserId         int64 `json:"userId"`
	FollowedUserId int64 `json:"followedUserId"`
}

type FollowRes struct {
}

type UnFollowReq struct {
	UserId         int64 `json:"userId"`
	FollowedUserId int64 `json:"followedUserId"`
}

type UnFollowRes struct {
}

type FollowItem struct {
}

type FollowListReq struct {
	UserId   int64 `json:"userId"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"pageSize"`
}

type FollowListRes struct {
	FollowList []FollowItem `json:"followList"`
	Cursor     int64        `json:"cursor"`
	IsEnd      bool         `json:"isEnd"`
}

type FansItem struct {
	FansUserId int64 `json:"fansUserId"`
}

type FansListReq struct {
	UserId   int64 `json:"userId"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"pageSize"`
}

type FansListRes struct {
	FansList []FansItem `json:"fansList"`
	Cursor   int64      `json:"cursor"`
	IsEnd    bool       `json:"isEnd"`
}

type Comment struct {
	PostID    int64  `json:"postId"`
	Pid       int64  `json:"pid"`
	CommentId int64  `json:"commentId"`
	Content   string `json:"content"`
}

type CommentReq struct {
	PostID    int64  `json:"postId"`
	Pid       int64  `json:"pid"`
	CommentId int64  `json:"commentId"`
	Content   string `json:"content"`
}

type CommentRes struct {
	CommentId int64 `json:"commentId"`
}

type CancelCommentReq struct {
}

type CancelCommentRes struct {
}

type CommentListReq struct {
	Ids []string `json:"ids"`
}

type CommentListRes struct {
	CommentList []Comment `json:"commentList"`
}

type CommentDetailReq struct {
}

type CommentDetailRes struct {
}

type DeleteCommentReq struct {
}

type DeleteCommentRes struct {
}

type CollectReq struct {
}

type CollectRes struct {
}

type CollectListReq struct {
}

type CollectListRes struct {
}
