// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GenerateTokenReq struct {
	UserId int64 `json:"userId,string"`
}

type GenerateTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Avatar        string `json:"avatar"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
	WorkCount     int64  `json:"work_count"`
}

type GetUserInfoReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserInfoRes struct {
	UserInfo User `json:"user_info"`
}

type UpdateUserInfoReq struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UpdateUserInfoRes struct {
}

type UplocadVideoReq struct {
}

type UplocadVideoRes struct {
	Avatar string `json:"avatar"`
}

type SendMsgReq struct {
}

type SendMsgRes struct {
}
