
CREATE TABLE `post` (
    `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
   `uid` int(11) NOT NULL COMMENT '作者id',
    `author_name` int(11) NOT NULL COMMENT '作者id',
   `topic_id` int(11) DEFAULT '0' COMMENT '分类id',
#    `discuss_id` int(11) DEFAULT '0' COMMENT '话题id',
   `title` varchar(50) DEFAULT '' COMMENT '标题',
   `content` longtext CHARACTER SET utf8mb4 COMMENT '内容',
   `media` text COMMENT '文件',
#    `read_count` int(255) DEFAULT '0' COMMENT '浏览量',
#    `post_top` int(1) DEFAULT '0' COMMENT '置顶',
   `type` int(1) DEFAULT '1' COMMENT '帖子类型：1图文2视频3文章',
#    `address` varchar(255) DEFAULT NULL COMMENT '地址名称',
#    `longitude` double(10,6) DEFAULT '0.000000' COMMENT '经度',
#    `latitude` double(10,6) DEFAULT '0.000000' COMMENT '纬度',
    `comment_num` int(11) NOT NULL DEFAULT '0' COMMENT '评论数',
    `like_num` int(11) NOT NULL DEFAULT '0' COMMENT '点赞数',
    `collect_num` int(11) NOT NULL DEFAULT '0' COMMENT '收藏数',
    `view_num` int(11) NOT NULL DEFAULT '0' COMMENT '浏览数',
    `share_num` int(11) NOT NULL DEFAULT '0' COMMENT '分享数',
    `tag_ids` varchar(255) NOT NULL DEFAULT '' COMMENT '标签ID',
    `publish_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
    `create_time` datetime DEFAULT NULL COMMENT '创建时间',
    `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    `status` int(1) NOT NULL DEFAULT '0' COMMENT '状态 0:待审核 1:审核不通过 2:可见 3:私密 4:用户删除',
   PRIMARY KEY (`id`) USING BTREE,
   KEY `uid` (`uid`) USING BTREE,
   KEY `topic_id` (`topic_id`) USING BTREE,
   KEY `status` (`status`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT COMMENT='帖子表';