// Code generated by goctl. DO NOT EDIT.
// Source: collect.proto

package server

import (
	"context"

	"video_clip/cmd/collect/rpc/collect"
	"video_clip/cmd/collect/rpc/internal/logic"
	"video_clip/cmd/collect/rpc/internal/svc"
)

type CollectServer struct {
	svcCtx *svc.ServiceContext
	collect.UnimplementedCollectServer
}

func NewCollectServer(svcCtx *svc.ServiceContext) *CollectServer {
	return &CollectServer{
		svcCtx: svcCtx,
	}
}

// 收藏
func (s *CollectServer) Collect(ctx context.Context, in *collect.CollectReq) (*collect.CollectRes, error) {
	l := logic.NewCollectLogic(ctx, s.svcCtx)
	return l.Collect(in)
}

// 取消收藏
func (s *CollectServer) UnCollect(ctx context.Context, in *collect.UnCollectReq) (*collect.UnCollectRes, error) {
	l := logic.NewUnCollectLogic(ctx, s.svcCtx)
	return l.UnCollect(in)
}

// 收藏列表
func (s *CollectServer) CollectList(ctx context.Context, in *collect.CollectListReq) (*collect.CollectListRes, error) {
	l := logic.NewCollectListLogic(ctx, s.svcCtx)
	return l.CollectList(in)
}
