// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"IkunHouse/cmd/msg/rpc/internal/logic"
	"IkunHouse/cmd/msg/rpc/internal/svc"
	msg2 "IkunHouse/cmd/msg/rpc/msg"
	"context"
)

type MsgServer struct {
	svcCtx *svc.ServiceContext
	msg2.UnimplementedMsgServer
}

func NewMsgServer(svcCtx *svc.ServiceContext) *MsgServer {
	return &MsgServer{
		svcCtx: svcCtx,
	}
}

func (s *MsgServer) Ping(ctx context.Context, in *msg2.Request) (*msg2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
