// Code generated by goctl. DO NOT EDIT.
// Source: search.proto

package searchClient

import (
	"context"

	"video_clip/cmd/search/rpc/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchShortVideoReq = search.SearchShortVideoReq
	SearchShortVideoRes = search.SearchShortVideoRes

	Search interface {
		SearchShortVideo(ctx context.Context, in *SearchShortVideoReq, opts ...grpc.CallOption) (*SearchShortVideoRes, error)
	}

	defaultSearch struct {
		cli zrpc.Client
	}
)

func NewSearch(cli zrpc.Client) Search {
	return &defaultSearch{
		cli: cli,
	}
}

func (m *defaultSearch) SearchShortVideo(ctx context.Context, in *SearchShortVideoReq, opts ...grpc.CallOption) (*SearchShortVideoRes, error) {
	client := search.NewSearchClient(m.cli.Conn())
	return client.SearchShortVideo(ctx, in, opts...)
}
