// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"video_clip/cmd/user/rpc/internal/logic"
	"video_clip/cmd/user/rpc/internal/svc"
	"video_clip/cmd/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 更新用户信息
func (s *UserServer) UpdateUserInfo(ctx context.Context, in *user.UpdateUserInfoReq) (*user.UpdateUserInfoRes, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

// 获取用户主页信息
func (s *UserServer) GetUserInfoDetail(ctx context.Context, in *user.GetUserInfoDetailReq) (*user.GetUserInfoDetailRes, error) {
	l := logic.NewGetUserInfoDetailLogic(ctx, s.svcCtx)
	return l.GetUserInfoDetail(in)
}
