// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"video_clip/cmd/user/rpc/internal/logic"
	"video_clip/cmd/user/rpc/internal/svc"
	"video_clip/cmd/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 批量获得用户信息接口
func (s *UserServer) MGetUserInfo(ctx context.Context, in *user.UserInfoRequest) (*user.UserInfoResponse, error) {
	l := logic.NewMGetUserInfoLogic(ctx, s.svcCtx)
	return l.MGetUserInfo(in)
}
