// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package commentclient

import (
	"context"

	"video_clip/cmd/comment/comment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = comment.Request
	Response = comment.Response

	Comment interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultComment struct {
		cli zrpc.Client
	}
)

func NewComment(cli zrpc.Client) Comment {
	return &defaultComment{
		cli: cli,
	}
}

func (m *defaultComment) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := comment.NewCommentClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
