// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"
	follow2 "video_clip/cmd/follow/rpc/follow"
	logic2 "video_clip/cmd/follow/rpc/internal/logic"
	"video_clip/cmd/follow/rpc/internal/svc"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	follow2.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

// 关注
func (s *FollowServer) Follow(ctx context.Context, in *follow2.FollowRequest) (*follow2.FollowResponse, error) {
	l := logic2.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

// 取消关注
func (s *FollowServer) UnFollow(ctx context.Context, in *follow2.UnFollowRequest) (*follow2.UnFollowResponse, error) {
	l := logic2.NewUnFollowLogic(ctx, s.svcCtx)
	return l.UnFollow(in)
}

// 关注列表
func (s *FollowServer) FollowList(ctx context.Context, in *follow2.FollowListRequest) (*follow2.FollowListResponse, error) {
	l := logic2.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}

// 粉丝列表
func (s *FollowServer) FansList(ctx context.Context, in *follow2.FansListRequest) (*follow2.FansListResponse, error) {
	l := logic2.NewFansListLogic(ctx, s.svcCtx)
	return l.FansList(in)
}
