// Code generated by goctl. DO NOT EDIT.
// Source: search.proto

package server

import (
	"context"

	"video_clip/cmd/search/rpc/internal/logic"
	"video_clip/cmd/search/rpc/internal/svc"
	"video_clip/cmd/search/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) SearchShortVideo(ctx context.Context, in *search.SearchShortVideoReq) (*search.SearchShortVideoRes, error) {
	l := logic.NewSearchShortVideoLogic(ctx, s.svcCtx)
	return l.SearchShortVideo(in)
}
