// Code generated by goctl. DO NOT EDIT.
// Source: auth.proto

package server

import (
	"context"
	auth2 "video_clip/cmd/auth/rpc/auth"
	"video_clip/cmd/auth/rpc/internal/logic"
	"video_clip/cmd/auth/rpc/internal/svc"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth2.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) Ping(ctx context.Context, in *auth2.Request) (*auth2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
