// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"video_clip/cmd/video/rpc/internal/logic"
	"video_clip/cmd/video/rpc/internal/svc"
	"video_clip/cmd/video/rpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) UploadVideo(ctx context.Context, in *video.UploadVideoRequest) (*video.UploadVideoResponse, error) {
	l := logic.NewUploadVideoLogic(ctx, s.svcCtx)
	return l.UploadVideo(in)
}

func (s *VideoServer) AddReadCount(ctx context.Context, in *video.AddReadCountRequest) (*video.AddReadCountResponse, error) {
	l := logic.NewAddReadCountLogic(ctx, s.svcCtx)
	return l.AddReadCount(in)
}

func (s *VideoServer) GetVideoList(ctx context.Context, in *video.GetVideoRequest) (*video.GetVideoResponse, error) {
	l := logic.NewGetVideoListLogic(ctx, s.svcCtx)
	return l.GetVideoList(in)
}

func (s *VideoServer) AddCollect(ctx context.Context, in *video.AddCollectRequest) (*video.AddCollectResponse, error) {
	l := logic.NewAddCollectLogic(ctx, s.svcCtx)
	return l.AddCollect(in)
}

func (s *VideoServer) GetCollectByVid(ctx context.Context, in *video.GetCollectByVidRequest) (*video.GetCollectByVidResponse, error) {
	l := logic.NewGetCollectByVidLogic(ctx, s.svcCtx)
	return l.GetCollectByVid(in)
}

func (s *VideoServer) GetCollectByUid(ctx context.Context, in *video.GetCollectByUidRequest) (*video.GetCollectByUidResponse, error) {
	l := logic.NewGetCollectByUidLogic(ctx, s.svcCtx)
	return l.GetCollectByUid(in)
}

func (s *VideoServer) GetTypeList(ctx context.Context, in *video.GetTypeListRequest) (*video.GetTypeListResponse, error) {
	l := logic.NewGetTypeListLogic(ctx, s.svcCtx)
	return l.GetTypeList(in)
}
