// Code generated by goctl. DO NOT EDIT.
// Source: auth.proto

package authclient

import (
	"context"
	auth2 "video_clip/cmd/auth/rpc/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = auth2.Request
	Response = auth2.Response

	Auth interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

func (m *defaultAuth) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := auth2.NewAuthClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
